# Generated by Django 5.2.8 on 2025-11-11 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endToEndId', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagador', models.JSONField()),
                ('recebedor', models.JSONField()),
                ('campoLivre', models.TextField(blank=True, null=True)),
                ('txId', models.CharField(max_length=50)),
                ('dataHoraPagamento', models.DateTimeField(auto_now_add=True)),
                ('visualizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PixStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ispb', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
